server:
  servlet:
    context-path: /spring-boot-aws

# JPA Config
spring.jpa.show-sql: true
# Strongly recommend to set this property to "none" in a production environment!
spring.jpa.hibernate.ddl-auto: update

spring.datasource:
  url: jdbc:mysql://localhost:3307/rds_demo
  username: root
  password: rootpwd
spring.datasource.hikari.initializationFailTimeout: 60000

aws:
  s3:
    region: ap-southeast-1
    endpoint: http://localhost:9001
    accessKeyId: minio
    secretAccessKey: minio123
    bucket: eppd-invoiceupload-local